package io.github.peppolnorway.spring.pipeline;

import io.github.peppolnorway.api.DocumentType;
import io.github.peppolnorway.spring.config.OxalisProperties;
import io.github.peppolnorway.spring.dto.SendResult;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import network.oxalis.ng.api.lang.OxalisContentException;
import network.oxalis.ng.api.lang.OxalisTransmissionException;
import network.oxalis.ng.api.lookup.LookupService;
import network.oxalis.ng.api.outbound.TransmissionResponse;
import network.oxalis.ng.api.outbound.TransmissionService;
import network.oxalis.vefa.peppol.common.model.*;
import network.oxalis.vefa.peppol.sbdh.SbdWriter;
import network.oxalis.vefa.peppol.sbdh.lang.SbdhException;
import network.oxalis.vefa.peppol.sbdh.util.XMLStreamUtils;
import org.springframework.stereotype.Service;

import javax.xml.stream.XMLStreamException;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Date;

/**
 * PEPPOL AS4 transmission pipeline implementing the <b>Pipeline pattern</b>.
 *
 * <p>Three explicit pipeline stages:</p>
 * <pre>
 * Stage 1: SMP Lookup  — verify receiver is registered in PEPPOL (configurable)
 * Stage 2: SBDH Wrap   — wrap the raw UBL XML in a Standard Business Document Header
 * Stage 3: AS4 Send    — transmit the SBDH-wrapped document to the receiver's AS4 endpoint
 * </pre>
 *
 * <p>Uses {@link DocumentType} as a Strategy parameter — different document types
 * (invoice, credit note, statistics report) require no conditional branching inside
 * the pipeline. The {@link DocumentType} enum carries all routing identifiers.</p>
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class PeppolTransmissionPipeline {

    /** ICD 0192 — Norwegian Register of Business Enterprises (Enhetsregisteret). */
    private static final String ICD_NO = "0192";

    /** ISO 3166-1 alpha-2 country code for Norway. Used in SBDH C1 country identifier. */
    private static final String COUNTRY_NO = "NO";

    private final TransmissionService transmissionService;
    private final LookupService lookupService;
    private final OxalisProperties properties;

    /**
     * Executes the complete PEPPOL send pipeline.
     *
     * @param xmlBytes     raw UBL XML bytes generated by {@link io.github.peppolnorway.builder.EhfDocumentService}
     * @param documentType PEPPOL document type (Strategy: carries all routing identifiers)
     * @param senderOrg    sender's Norwegian organization number (9 digits, no prefix)
     * @param receiverOrg  receiver's Norwegian organization number (9 digits, no prefix)
     * @return transmission result encapsulating success, failure, or non-registration
     */
    public SendResult send(byte[] xmlBytes, DocumentType documentType,
                           String senderOrg, String receiverOrg) {
        String messageId = null;
        try {
            // Stage 1: SMP lookup (configurable via oxalis.lookupBeforeSend)
            if (properties.isLookupBeforeSend()) {
                if (!isReceiverRegistered(receiverOrg, documentType)) {
                    return SendResult.receiverNotRegistered(receiverOrg);
                }
            }

            // Stage 2: Build PEPPOL SBDH routing header
            Header header = buildHeader(senderOrg, receiverOrg, documentType);
            messageId = header.getIdentifier().getIdentifier();

            // Stage 3: Wrap the UBL XML in an SBDH envelope
            byte[] sbdhBytes = wrapInSbdh(xmlBytes, header);
            log.debug("SBDH wrap complete [{} bytes] | messageId={}", sbdhBytes.length, messageId);

            // Stage 4: Transmit via Oxalis AS4
            TransmissionResponse response;
            try (InputStream inputStream = new ByteArrayInputStream(sbdhBytes)) {
                response = transmissionService.send(inputStream);
            }

            log.info("PEPPOL send success | type={} | sender={} | receiver={} | messageId={}",
                    documentType.name(), senderOrg, receiverOrg, messageId);

            return SendResult.success(messageId, response);

        } catch (OxalisTransmissionException e) {
            log.error("AS4 transmission failed | messageId={} | cause={}", messageId, e.getMessage(), e);
            return SendResult.transmissionFailed(messageId, e.getMessage());

        } catch (OxalisContentException e) {
            log.error("PEPPOL content validation failed | messageId={} | cause={}", messageId, e.getMessage(), e);
            return SendResult.contentFailed(messageId, e.getMessage());

        } catch (IOException e) {
            log.error("I/O error during transmission | messageId={} | cause={}", messageId, e.getMessage(), e);
            return SendResult.transmissionFailed(messageId, "I/O error: " + e.getMessage());
        }
    }

    /**
     * Queries the PEPPOL SMP to verify that the specified receiver organization
     * is registered and can receive documents of the given type.
     *
     * <p>Returns {@code false} on any exception, treating lookup failures as
     * non-registration (fail-safe behaviour).</p>
     *
     * @param receiverOrg  receiver's Norwegian organization number
     * @param documentType document type to look up capability for
     * @return true if the receiver is registered in PEPPOL for this document type
     */
    public boolean isReceiverRegistered(String receiverOrg, DocumentType documentType) {
        String receiverId = documentType.getReceiverIcd() + ":" + receiverOrg;
        try {
            Endpoint endpoint = lookupService.lookup(Header.newInstance()
                    .receiver(ParticipantIdentifier.of(receiverId))
                    .documentType(DocumentTypeIdentifier.of(documentType.getDocTypeId()))
                    .process(ProcessIdentifier.of(documentType.getProcessId())));

            boolean registered = endpoint != null;
            log.info("SMP lookup | receiver={} | type={} | registered={}",
                    receiverId, documentType.name(), registered);
            return registered;

        } catch (OxalisTransmissionException e) {
            log.debug("SMP lookup: receiver {} not registered. Reason: {}", receiverId, e.getMessage());
            return false;
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Private pipeline stage implementations
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Builds the PEPPOL SBDH routing header from the DocumentType strategy.
     * No if/switch is needed — DocumentType carries all required identifiers.
     */
    private Header buildHeader(String senderOrg, String receiverOrg, DocumentType documentType) {
        return Header.newInstance()
                .sender(ParticipantIdentifier.of(ICD_NO + ":" + senderOrg))
                .receiver(ParticipantIdentifier.of(documentType.getReceiverIcd() + ":" + receiverOrg))
                .process(ProcessIdentifier.of(documentType.getProcessId()))
                .documentType(DocumentTypeIdentifier.of(
                        documentType.getDocTypeId(),
                        DocumentTypeIdentifier.BUSDOX_DOCID_QNS_SCHEME))
                .instanceType(InstanceType.of(
                        documentType.getInstanceTypeId(),
                        documentType.getLocalName(),
                        documentType.getVersion()))
                .creationTimestamp(new Date())
                .c1CountryIdentifier(C1CountryIdentifier.of(COUNTRY_NO))
                .identifier(InstanceIdentifier.generateUUID());
    }

    /**
     * Wraps the raw UBL XML bytes in a PEPPOL SBDH (Standard Business Document Header) envelope.
     *
     * @param xmlBytes raw UBL XML
     * @param header   pre-built SBDH routing header
     * @return SBDH-wrapped bytes ready for AS4 transmission
     */
    private byte[] wrapInSbdh(byte[] xmlBytes, Header header) throws IOException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (SbdWriter sbdWriter = SbdWriter.newInstance(out, header);
             InputStream xmlInput = new ByteArrayInputStream(xmlBytes)) {
            XMLStreamUtils.copy(xmlInput, sbdWriter.xmlWriter());
        } catch (SbdhException | XMLStreamException e) {
            throw new RuntimeException("Failed to wrap UBL XML in SBDH envelope: " + e.getMessage(), e);
        }
        return out.toByteArray();
    }
}
